---
title: Book Notes
description: Notes on books about independent consulting
---

### 100M Offers [^1]

-  Don't sell work by the hour that isn't tied to results. This is what everyone else is doing and leads to bad offers. People should be buying results, not time. This must be coupled with charging more. [^1]
    -  I find this particularly hard to do because results for AI projects are often hard to predict and have long time horizons.
-  Find the right market (starving crowd + purchasing power): don't sell to series A startups.
-  Niche down: "AI for Private Equity"
-  If you are competing on price that is a smell that your offer is bad.
-  Process: Goals -> Problems -> Solutions.
    -  Create a list of solutions by appending "How To" to the problems.
-  Offer: Solutions -> Delivery -> Filter & Bundle
    - Delivery: ex: Excel spreadsheet, 1:1 coaching, online course, etc.
    Filter: axe low-value, low-cost or low-value, high-cost items.  You are left with high-value low-cost and high-value high-cost items.  
    - Bundle: Sexier name for a group of solutions -> "Foolproof Bargain Grocery System"
- **Scarcity:** Always sell out, don't be available all the time.
    - Let people know when you are sold out - esp those who are on the fence.
    - Only accepting X clients, only can handle one more project at this level.  Let them know you are at capacity.
- **Urgency:**
    - Exploding opportunity
- Enhancing the Offer: 
    - Tell them the bonuses they are getting _after_ they agree, to mitigate cognitive dissonance.
    - Add a bonus to overcome an objection and ask if it's "enough to make you say yes?"
    - Bonuses:
        - Record every talk, workshop, or training you do and sell it as a bonus.
        - 1:1 coaching
        - Guarantee
        - Advanced: other people's products and services
    - Offering bonuses:
        - Tell them how it relates to their issue, what it is, how you discovered it, or what you had to do to create it. 
        - Tell them them how it will specifically improve their life or make their experience faster, easier or more enjoyable.
        - Tools & checklists are better than additional time.


Summary of the book:
    1. We covered why you must not be a commodity in this marketplace.
    2. Why you should pick a normal or growing market, and why niches get you riches.
    3. Why you should charge a lot of money.
    4. How to charge a lot of money using the four core value drivers.
    5. How to create your value offer in five steps.
    6. How to stack the value, deliver it, and make it profitable.
    7. How to shift the demand curve in your favor using scarcity.
    8. How to use urgency to decrease the action threshold of buyers.
    9. How to strategically use bonuses to increase the demand of your offer.
    10. How to completely reverse buyer risk with a creative guarantee.


[^1]: [100M offers](https://www.amazon.com/100M-Offers-People-Stupid-Saying/dp/1737475731)

