project:
  type: book
  output-dir: _book

book:
  title: "Retrieval Augmented Generation (RAG)"
  subtitle: "From Fundamentals to Advanced Techniques"
  author: "Hamel Husain"
  date: "2025-08-06"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/ch1-not-dead.qmd
        - chapters/ch2-intro.qmd
    - part: "Advanced Techniques"
      chapters:
        - chapters/ch3-evals.qmd
        - chapters/ch4-reasoning.qmd
        - chapters/ch5-late-interaction.qmd
        - chapters/ch6-map.qmd
  
format:
  pdf:
    documentclass: scrbook
    classoption: [oneside]
    toc-depth: 3
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \usepackage{fancyhdr}
        \usepackage{xcolor}
        \usepackage{booktabs}
        \usepackage{graphicx}
        \makeindex
        \pagestyle{fancy}
        \fancyhead[LE,RO]{\thepage}
        \fancyhead[RE]{\textit{\leftmark}}
        \fancyhead[LO]{\textit{\rightmark}}
    include-before-body: 
      text: |
        \begin{titlepage}
        \centering
        \vspace*{3cm}
        {\Huge\bfseries Retrieval Augmented Generation (RAG)\par}
        \vspace{1cm}
        {\Large From Fundamentals to Advanced Techniques\par}
        \vspace{2cm}
        {\Large Hamel Husain\par}
        \vspace{1cm}
        {\large \today\par}
        \vspace{2cm}
        {\large A comprehensive guide to understanding and implementing\\ Retrieval Augmented Generation systems\par}
        \end{titlepage}