---
title: Guest Blogs
description: Blog posts I have written on other sites
---

- [nbdev + Quarto: A new secret weapon for productivity](https://www.fast.ai/2022/07/28/nbdev-v2/), the fastai blog, July 2022.

- [Notebooks in production with Metaflow](https://outerbounds.com/blog/notebooks-in-production-with-metaflow/) Introduces a new Metaflow feature that allows users to use notebooks in production ML workflows.

- [Python Concurrency: The Tricky Bits](https://python.hamel.dev/concurrency/): An exploration of threads, processes, and coroutines in Python, with interesting examples that illuminate the differences between each.

- [ghapi, a new third-party Python client for the GitHub API](https://github.blog/2020-12-18-learn-about-ghapi-a-new-third-party-python-client-for-the-github-api/) by _Jeremy Howard & Hamel Husain_, [GitHub Repo](https://github.com/fastai/ghapi).

- [Nbdev: A literate programming environment that democratizes software engineering best practices](https://github.blog/2020-11-20-nbdev-a-literate-programming-environment-that-democratizes-software-engineering-best-practices/) by _Hamel Husain, Jeremy Howard_, The GitHub Blog.

- [fastcore: An Underrated Python Library](https://fastpages.fast.ai/fastcore/) by _Hamel Husain, Jeremy Howard_, [GitHub Repo](https://github.com/fastai/fastcore).

- [Data Science Meets Devops: MLOps with Jupyter, Git, & Kubernetes](https://blog.kubeflow.org/mlops/): An end-to-end example of deploying a machine learning product using Jupyter, Papermill, Tekton, GitOps and Kubeflow. by _Jeremy Lewi, Hamel_Husain_, The Kubeflow Blog.  

- [Introducing fastpages, An easy to use blogging platform with extra features for Jupyter Notebooks.](https://fastpages.fast.ai/fastpages/jupyter/2020/02/21/introducing-fastpages.html) by _Jeremy Howard & Hamel Husain_, [GitHub Repo](https://github.com/fastai/fastpages)

- [GitHub Actions: Providing Data Scientists With New Superpowers](https://fastpages.fast.ai/actions/markdown/2020/03/06/fastpages-actions.html) by _Jeremy Howard & Hamel Husain_.

- [CodeSearchNet Challenge: Evaluating the State of Semantic Code Search](https://arxiv.org/abs/1909.09436): by _Miltiadis Allamanis, Marc Brockschmidt, Hamel Husain, Ho-Hsiang Wu, Tiferet Gazit_ [GitHub Repo](https://github.com/github/codesearchnet)


- [How To Create Natural Language Semantic Search for Arbitrary Objects With Deep Learning](https://medium.com/@hamelhusain/semantic-code-search-3cd6d244a39c).  (_Related: GitHub engineering_ [_blog article_](https://githubengineering.com/towards-natural-language-semantic-code-search/),  _Live_ [_demo_](https://experiments.github.com/semantic-code-search))

- [How To Create Magical Data Products Using Sequence-to-Sequence Models](https://towardsdatascience.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8)

- [How to Automate Tasks on GitHub With Machine Learning for Fun and Profit](https://medium.com/@hamelhusain/mlapp-419f90e8f007?source=friends_link&sk=760e18a2d6e60999d7eb2887352a92a8)

- [How Docker Can Make You A More Effective Data Scientist](https://towardsdatascience.com/how-docker-can-help-you-become-a-more-effective-data-scientist-7fc048ef91d5)

- [Automated Machine Learning, A Paradigm Shift That Accelerates Data Scientst Productivity At Airbnb](https://medium.com/airbnb-engineering/automated-machine-learning-a-paradigm-shift-that-accelerates-data-scientist-productivity-airbnb-f1f8a10d61f8)