---
title: Talks
sidebar: false
---

These are a list of talks I've given:

- [AutoML, Literate Programming, and Data Tooling Cargo Cults](https://vanishinggradients.fireside.fm/9), Vanishing Gradients Podcast with Hugo Bowne Anderson, July 2022.

- How to evaluate ML Tooling: Guest Lecutre for Stanford CS 329S ML Systems Design, Feb 2022. [Slides](https://docs.google.com/presentation/d/1BVWmp7pfEp6_ffilcvz--_KbFqK-c9bElfbuxHFWPKo/edit?usp=sharing), [Video](https://youtu.be/GHk5HMW4XMA)

- JupyterCon 2020: "fastpages - A new, open source Jupyter notebook blogging system.".  [Slides](http://bit.ly/jc-fastpages), [Video](https://www.youtube.com/watch?v=cduXZwZaBbM).

- Gradient Descent by Weights & Biases: A discussion on Automated Machine Learning, CodeSearchNet, GitHub Actions and MLOps: [Video](https://youtu.be/TMe8xz4cUKs)

- GitHub Universe 2019: "Machine Learning Ops With GitHub Actions & Kubernetes".  [Video](https://youtu.be/Ll50l3fsoYs)

- TensorFlow World, 2019: "Automating your developer workflow on GitHub with Tensorflow".  [Slides](http://bit.ly/tf-github), [Link](https://conferences.oreilly.com/tensorflow/tf-ca-2019/public/schedule/detail/78380)

- [Data Skeptic Interview, Jan 2018](http://dataskeptic.com/blog/episodes/2019/semantic-search-at-github):  "Semantic Search at Github".

- [KubeCon 2018](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/), "Natural Language Code Search With Kubeflow". [Slides](https://docs.google.com/presentation/d/1jHE61fAqZNgaDrpItk5L_tCzLU0DuL86rCz4yAKz4Ss/edit?usp=sharing), [Video](https://www.youtube.com/watch?v=SF77UBvfTHU)

- [KDD, London August 2018](http://www.kdd.org/kdd2018/):  Hands on tutorial, "Feature Extraction and Summarization With Sequence to Sequence Learning".  [Tutorial-site](https://kddseq2seq.com/)

 - [Ml4all, Portland May 2018](http://ml4all.org/): "How to Create Magical Data Products Using Sequence-to-Sequence Models".  [Slides](https://docs.google.com/presentation/d/1pqkOWcIjpaXJPiP3_MT9KrdiZd0LoAWxh6Ei28i4CM8/edit?usp=sharing),  [Video](https://www.youtube.com/watch?v=t063URlwyFM)
 
 - [ODSC, San Francisco Nov 2017](https://old.opendatascience.com/conferences/advice-for-new-and-junior-data-scientists-hamel-husain-l-odsc-west-2017/): "Advice For New And Junior Data Scientists" [Video](https://www.youtube.com/watch?v=eDK1R6tpZlA&feature=youtu.be)
